# Generated by Django 4.0.4 on 2022-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dueño',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='vacunador',
            field=models.BooleanField(default=False),
        ),
    ]
