# Generated by Django 4.0.4 on 2022-05-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aplicacion_centrodevacunacion_dueno_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunasanteriores',
            name='nombre_vacuna',
        ),
    ]
