<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-21 14:27
=======
# Generated by Django 4.0.4 on 2022-05-15 22:30
>>>>>>> 856d9a216734950c926e57902d9746624bca4538

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_vacunasanteriores_nombre_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunasanteriores',
            name='user',
<<<<<<< HEAD
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> 856d9a216734950c926e57902d9746624bca4538
            preserve_default=False,
        ),
    ]
