# Generated by Django 4.0.4 on 2022-05-15 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_vacunasanteriores_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunasanteriores',
            name='covid_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vacunasanteriores',
            name='covid_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vacunasanteriores',
            name='fiebre_amarilla',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vacunasanteriores',
            name='gripe',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vacunasanteriores',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
