# Generated by Django 4.0.4 on 2022-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vacunasanteriores_covid_1_vacunasanteriores_covid_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
