# Generated by Django 4.0.4 on 2022-05-19 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='id_vacunador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacunador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientevacunas',
            name='nombre_vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientevacunas',
            name='nombreusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajaen',
            name='nombrecentro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.centrodevacunacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajaen',
            name='nombreusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vacunador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='nombreusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.paciente'),
            preserve_default=False,
        ),
    ]
