# Generated by Django 4.0.4 on 2022-05-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_aplicacion_id_paciente_aplicacion_id_vacunador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No Binario'), ('NC', 'No Contesta')], default='NC', max_length=2),
        ),
        migrations.AlterField(
            model_name='pacientevacunas',
            name='nombreusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paciente'),
        ),
    ]
