# Generated by Django 4.0.4 on 2022-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_aplicacion_id_paciente_aplicacion_id_vacunador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
