# Generated by Django 4.0.4 on 2022-05-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_paciente_sexo_alter_pacientevacunas_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientevacunas',
            name='nombre_vacuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vacuna'),
        ),
    ]
