# Generated by Django 4.0.4 on 2022-05-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_paciente_centro_vacunacion_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
    ]
