# Generated by Django 4.0.4 on 2022-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('NB', 'No Binario'), ('NC', 'No Contesta')], default='NC', max_length=2),
        ),
    ]
