# Generated by Django 4.0.4 on 2022-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=150, null=True, unique=True),
        ),
    ]
