# Generated by Django 4.0.4 on 2022-05-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_paciente_email'),
        ('accounts', '0011_alter_paciente_email'),
    ]

    operations = [
    ]
