# Generated by Django 4.0.4 on 2022-05-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_vacunasanteriores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
    ]
