# Generated by Django 4.0.4 on 2022-05-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_paciente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
