# Generated by Django 4.0.4 on 2022-06-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='centro',
            field=models.ForeignKey(default='Bosque', on_delete=django.db.models.deletion.CASCADE, to='accounts.centrodevacunacion'),
        ),
    ]
