# Generated by Django 4.0.4 on 2022-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_turno_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='validado_renaper',
            field=models.BooleanField(default=False),
        ),
    ]
